export enum JobStatus {
  NOT_PUBLISHED = 'NOT_PUBLISHED',
  ACCEPTING_APPLICATIONS = 'ACCEPTING_APPLICATIONS',
  SHORT_LISTING = 'SHORT_LISTING',
  CONDUCTING_INTERVIEWS = 'CONDUCTING_INTERVIEWS',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}
